export default {
   purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
   darkMode: false, // or 'media' or 'class'
   theme: {
      extend: {
         keyframes: {
            moveUpDown: {
               "0%, 100%": { transform: "translateY(0)" },
               "50%": { transform: "translateY(-20px)" },
            },
         },
         animation: {
            "move-up-down": "moveUpDown 2s ease-in-out infinite",
         },
      },
      fontSize: {
         xs: ".75rem",
         sm: ".875rem",
         tiny: ".875rem",
         base: "1rem",
         lg: "1.125rem",
         xl: "1.25rem",
         "2xl": "1.5rem",
         "3xl": "1.875rem",
         "4xl": "2.25rem",
         "5xl": "3rem",
         "6xl": "4rem",
         "7xl": "5rem",
         "8xl": "6rem",
         "9xl": "7rem",
         "10xl": "8rem",
         "11xl": "9rem",
         "12xl": "10rem",
         "13xl": "11rem",
         "14xl": "12rem",
         "15xl": "13rem",
         "16xl": "14rem",
         "17xl": "15rem",
         "18xl": "16rem",
         "19xl": "17rem",
         "20xl": "18rem",
         "21xl": "19rem",
         "22xl": "20rem",
         "23xl": "21rem",
         "24xl": "22rem",
         "25xl": "23rem",
         "26xl": "24rem",
         "27xl": "25rem",
         "28xl": "26rem",
         "29xl": "27rem",
         "30xl": "28rem",
      },
      variants: {
         extend: {},
      },
      plugins: [],
   },
};
